<?php 
ini_set('memory_limit', '-1');
header('Content-Type: text/html; charset=UTF-8');

$path='/xampp/htdocs/phpFunctions/NPX/npxSample/';
$file='fenwayfunds0065.htm - Generated by SEC Publisher for SEC Filing.htm';
$npxC=file_get_Contents($path.$file);
$npxC=preg_replace('/\&nbsp\;/', ' ',$npxC);
$npxC=preg_replace('/\&amp\;/', '&',$npxC);

$npx=strip_tags($npxC);

$row=explode("\n",$npx);


$fundId=0;
$fundIds=0;
$compId=0;	
$start=333;
$resNr=0;
//Delimiters

$headerDelim="PROPOSAL:                                                                             PROPOSED BY   VOTED?    VOTE CAST          MGMT ";



for($i=0;$i<count($row);$i++)
{

	//Grab Fund Name + Fund Id
	if(strpos($row[$i],"FUND: ")!==false)
	{
		$fundName[]=trim( str_replace("FUND: ","",$row[$i]));
		$fundIds++;
		$fundId=$fundIds-1;
		if(trim($row[$i+1]))
		{
			$fundName[$fundId].=" ".trim($row[$i+1]);
		}

		$compId=0;		
	}


	//Get MEETING INFOs
	if(strpos($row[$i],"------")!=false)
	{
		$resNr=0;
		$start=1;
		$compName[$fundId][]=trim(str_replace("ISSUER:","",$row[$i+2]));
		
		if(trim($row[$i+3]))
		{
			$compName[$fundId][$compId].=" ".trim($row[$i+3]);	
		}
		$compId++;

		if(strpos($row[$i+4],"TICKER:")!=false)
		{
			$tick=explode("CUSIP:",$row[$i+4]);
			$tickerName[$fundId][]=trim(str_replace("TICKER:","",$tick[0]));
			$secId[$fundId][]=trim($tick[1]);			
		}
		elseif(strpos($row[$i+5],"TICKER:")!=false)
		{
			$tick=explode("CUSIP:",$row[$i+5]);
			$tickerName[$fundId][]=trim(str_replace("TICKER:","",$tick[0]));
			$secId[$fundId][]=trim($tick[1]);			
		}

		if(strpos($row[$i+6],"MEETING DATE:")!=false)
		{
			$meetDate[$fundId][]=trim(str_replace("FOR/AGAINST","",str_replace("MEETING DATE:","",$row[$i+6])));
		}
		elseif(strpos($row[$i+7],"MEETING DATE:")!=false)
		{
			$meetDate[$fundId][]=trim(str_replace("FOR/AGAINST","",str_replace("MEETING DATE:","",$row[$i+7])));
		}

	}

	//Get Vote Details
		//Reformat Proposal	
		if(substr($row[$i],0,10)=="PROPOSAL #")
		{
			$break=explode(" #",$row[$i]);
			$row[$i]=$break[0];
			$row[$i+1]="#".$break[1]." ".$row[$i+1];
			unset($break);

		}
		

			if(substr($row[$i],0,1)=="#")
			{
				$start=1;
				$linea=explode(":",$row[$i],2);
				$resId[$fundId][$compId-1][$resNr]=substr($linea[0],1);

				//Issuer vs Shareholder
				if(strpos($row[$i],"  ISSUER  ")!==false)
				{
					$sponsor[$fundId][$compId-1][$resNr]="ISSUER";
					$proposala=explode("  ISSUER  ",$linea[1]);
					$proposal[$fundId][$compId-1][$resNr]=trim($proposala[0]);
				}
				elseif(strpos($row[$i],"  SHAREHOLDER  ")!==false)
				{
					$sponsor[$fundId][$compId-1][$resNr]="SHAREHOLDER";
					$proposala=explode("  SHAREHOLDER  ",$linea[1]);
					$proposal[$fundId][$compId-1][$resNr]=trim($proposala[0]);					
				}
				unset($proposala);
				//Votes and Mgmt Rec
				$lineb= preg_split( "/ (\s\YES\s\s|\s\sNO\s\s) /", $linea[1] );
				$lineb[1]=preg_replace('!\s\s+!',"  ",$lineb[1]);
				$linec=preg_split( "/\s\s/", $lineb[1] );

				$voteCast[$fundId][$compId-1][$resNr]=$linec[1];	
				$mgmtRec[$fundId][$compId-1][$resNr]=$linec[2];	

				$resNr++;

			}
			
			if($start==1 && substr($row[$i],0,8)!="PROPOSAL" && substr($row[$i],0,1)!="#"  && trim($row[$i])!="SIGNATURES" && trim($row[$i])) 
			{
				if(strpos($row[$i],"------")!=false)
				{
				}
				else
				{
					$proposal[$fundId][$compId-1][$resNr-1].=" ".trim($row[$i]);
				}
			}
		
		if(substr($row[$i],0,8)=="PROPOSAL" || strpos($row[$i],"------")!=false || trim($row[$i])=="SIGNATURES")
		{
			$start=0;
		}




}
echo "<table>";
$i=0;
foreach($resId as $res)
{
	$j=0;
	foreach($res as $re)
	{	
		$k=0;

		foreach($re as $r)
		{
			echo "<tr>";
			echo "<td>".$fundName[$i]."</td>";
			echo "<td>".$compName[$i][$j]."</td>";
			echo "<td>".$tickerName[$i][$j]."</td>";
			echo "<td>".$meetDate[$i][$j]."</td>";

								
			echo "<td>".$secId[$i][$j]."</td>";																	
			echo "<td>".$r."</td>";
			echo "<td>".$proposal[$i][$j][$k]."</td>";
			echo "<td>".$mgmtRec[$i][$j][$k]."</td>";
			echo "<td>".$voteCast[$i][$j][$k]."</td>";
			echo "<td>".$sponsor[$i][$j][$k]."</td>";										
			echo "</tr>";
			$k++;
		}

		$j++;
	}
	$i++;
}
echo "</table>";
?>